# Generated by Django 4.1.1 on 2022-10-01 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='phoneNum',
            new_name='mobile',
        ),
    ]
