# Generated by Django 4.1.1 on 2022-10-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_rename_phonenum_guest_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='mobile',
        ),
        migrations.AddField(
            model_name='guest',
            name='age',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
